services:
  - type: web
    name: pdf-tools
    runtime: python
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright

    buildCommand: bash build.sh

    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
