services:
  - type: web
    name: pdf-tools
    runtime: python

    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.playwright

      - key: SECRET_KEY
        value: your-secret-key

    buildCommand: bash build.sh

    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120